# Generated by Django 5.0 on 2023-12-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('is_done', models.CharField(choices=[('done', 'DONE'), ('not_done', 'NOT DONE'), ('processing', 'PROCESSING'), ('canceled', 'CANCELED')], max_length=10, verbose_name='Этап выполнения задачи')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='Срок выполнения задачи')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания задачи')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения задачи')),
                ('list', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tasks', to='lists.list', verbose_name='Список задач')),
            ],
        ),
    ]
