# Generated by Django 3.1.14 on 2023-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('1', 'Высший'), ('2', 'Высокий'), ('3', 'Низкий'), ('4', 'Без приоритета')], default='1', verbose_name='Уровень приоритета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
