# Generated by Django 3.1.14 on 2024-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20231229_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.CharField(blank=True, choices=[('done', 'DONE'), ('not_done', 'NOT DONE'), ('processing', 'PROCESSING'), ('canceled', 'CANCELED')], default='not_done', max_length=10, verbose_name='Этап выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('1', 'Высший'), ('2', 'Средний'), ('3', 'Низкий'), ('4', 'Без приоритета')], default='1', verbose_name='Уровень приоритета'),
        ),
    ]
