# Generated by Django 3.1.14 on 2024-01-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20240128_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, choices=[('1', 'Высший'), ('2', 'Средний'), ('3', 'Низкий'), ('4', 'Без приоритета')], default='1', verbose_name='Уровень приоритета'),
        ),
    ]
