# Generated by Django 3.1.14 on 2024-01-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20240128_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='stage',
        ),
    ]
